#include "WGameObjectManager.h"
#include "WGameObject.h"
#include "ObjectHeader.h"

#define REGISTER_OBJECT_ID(name, id)\
{ name::SET_CREATE_ID(id); };

namespace W
{
	void GameObjectManager::Initialize()
	{
		REGISTER_OBJECT_ID	(GameObject			 , 0  )
		REGISTER_OBJECT_ID	(Abnormal			 , 1  )
		REGISTER_OBJECT_ID	(Ariel				 , 2  )
		REGISTER_OBJECT_ID	(ArielLaser			 , 3  )
		REGISTER_OBJECT_ID	(ArielStone			 , 4  )
		REGISTER_OBJECT_ID	(AttackUp			 , 5  )
		REGISTER_OBJECT_ID	(AutoShuriken		 , 6  )
		REGISTER_OBJECT_ID	(Aven				 , 7  )
		REGISTER_OBJECT_ID	(Blast				 , 8  )
		REGISTER_OBJECT_ID	(Cage				 , 9  )
		REGISTER_OBJECT_ID	(CloneMegnus		 , 10 )
		REGISTER_OBJECT_ID	(Confusion			 , 11 )
		REGISTER_OBJECT_ID	(DefenseUp			 , 12 )
		REGISTER_OBJECT_ID	(Demian				 , 13 )
		REGISTER_OBJECT_ID	(DemianCircle		 , 14 )
		REGISTER_OBJECT_ID	(DemianEntireAttack	 , 15 )
		REGISTER_OBJECT_ID	(DemianExplode		 , 16 )
		REGISTER_OBJECT_ID	(DemianFire0		 , 17 )
		REGISTER_OBJECT_ID	(DemianFire1		 , 18 )
		REGISTER_OBJECT_ID	(DemianFire2		 , 19 )
		REGISTER_OBJECT_ID	(DemianKeyAttack	 , 20 )
		REGISTER_OBJECT_ID	(DemianPhase2		 , 21 )
		REGISTER_OBJECT_ID	(DemianSpear0		 , 22 )
		REGISTER_OBJECT_ID	(DemianSpear1		 , 23 )
		REGISTER_OBJECT_ID	(DemianSword		 , 24 )
		REGISTER_OBJECT_ID	(DemianVine			 , 25 )
		REGISTER_OBJECT_ID	(Effect				 , 26 )
		REGISTER_OBJECT_ID	(Eyes				 , 27 )
		REGISTER_OBJECT_ID	(Faint				 , 28 )
		REGISTER_OBJECT_ID	(Fire				 , 29 )
		REGISTER_OBJECT_ID	(Groggy				 , 30 )
		REGISTER_OBJECT_ID	(Ground				 , 31 )
		REGISTER_OBJECT_ID	(Horntail			 , 32 )
		REGISTER_OBJECT_ID	(HorntailHeadA		 , 33 )
		REGISTER_OBJECT_ID	(HorntailHeadB		 , 34 )
		REGISTER_OBJECT_ID	(HorntailHeadC		 , 35 )
		REGISTER_OBJECT_ID	(HorntailLeftHand	 , 36 )
		REGISTER_OBJECT_ID	(HorntailLeg		 , 37 )
		REGISTER_OBJECT_ID	(HorntailRightHand	 , 38 )
		REGISTER_OBJECT_ID	(HorntailTail		 , 39 )
		REGISTER_OBJECT_ID	(HorntailWing		 , 40 )
		REGISTER_OBJECT_ID	(Ice				 , 41 )
		REGISTER_OBJECT_ID	(Ignore				 , 42 )
		REGISTER_OBJECT_ID	(InputBackground	 , 43 )
		REGISTER_OBJECT_ID	(InputObject		 , 44 )
		REGISTER_OBJECT_ID	(Jenesis			 , 45 )
		REGISTER_OBJECT_ID	(Ladder				 , 46 )
		REGISTER_OBJECT_ID	(Load				 , 47 )
		REGISTER_OBJECT_ID	(Megnus				 , 48 )
		REGISTER_OBJECT_ID	(MegnusAttack		 , 49 )
		REGISTER_OBJECT_ID	(MegnusStone		 , 50 )
		REGISTER_OBJECT_ID	(MiniBean			 , 51 )
		REGISTER_OBJECT_ID	(MiniBeanAttack		 , 52 )
		REGISTER_OBJECT_ID	(MobZone			 , 53 )
		REGISTER_OBJECT_ID	(Monster			 , 54 )
		REGISTER_OBJECT_ID	(MonsterAttackObject , 55 )
		REGISTER_OBJECT_ID	(MonsterBackHP		 , 56 )
		REGISTER_OBJECT_ID	(MonsterHP			 , 57 )
		REGISTER_OBJECT_ID	(MonsterMoveAttack	 , 58 )
		REGISTER_OBJECT_ID	(Munin				 , 59 )
		REGISTER_OBJECT_ID	(MuninStone			 , 60 )
		REGISTER_OBJECT_ID	(PinkBean			 , 61 )
		REGISTER_OBJECT_ID	(PinkBeanStone		 , 62 )
		REGISTER_OBJECT_ID	(Player				 , 63 )
		REGISTER_OBJECT_ID	(PlayerArm			 , 64 )
		REGISTER_OBJECT_ID	(PlayerAttackObject	 , 65 )
		REGISTER_OBJECT_ID	(PlayerBody			 , 66 )
		REGISTER_OBJECT_ID	(PlayerBottom		 , 67 )
		REGISTER_OBJECT_ID	(PlayerHair			 , 68 )
		REGISTER_OBJECT_ID	(PlayerHat			 , 69 )
		REGISTER_OBJECT_ID	(PlayerHead			 , 70 )
		REGISTER_OBJECT_ID	(PlayerShoes		 , 71 )
		REGISTER_OBJECT_ID	(PlayerTop			 , 72 )
		REGISTER_OBJECT_ID	(PlayerWeapon		 , 73 )
		REGISTER_OBJECT_ID	(PullObject			 , 74 )
		REGISTER_OBJECT_ID	(Reflex				 , 75 )
		REGISTER_OBJECT_ID	(Rex				 , 76 )
		REGISTER_OBJECT_ID	(RexThunder			 , 77 )
		REGISTER_OBJECT_ID	(RoccatBean			 , 78 )
		REGISTER_OBJECT_ID	(SealSkill			 , 79 )
		REGISTER_OBJECT_ID	(Shadow				 , 80 )
		REGISTER_OBJECT_ID	(SharHP				 , 81 )
		REGISTER_OBJECT_ID	(Shuriken			 , 82 )
		REGISTER_OBJECT_ID	(Skelegon			 , 83 )
		REGISTER_OBJECT_ID	(SleepGas			 , 84 )
		REGISTER_OBJECT_ID	(Slow				 , 85 )
		REGISTER_OBJECT_ID	(SolThunder			 , 86 )
		REGISTER_OBJECT_ID	(Solomon			 , 87 )
		REGISTER_OBJECT_ID	(SpawnMonsterAttack	 , 88 )
		//REGISTER_OBJECT_ID	(SpawnUltimate		 , 89 )
		REGISTER_OBJECT_ID	(Spear				 , 90 )
		REGISTER_OBJECT_ID	(Stigma				 , 91 )
		REGISTER_OBJECT_ID	(StigmaBack			 , 92 )
		REGISTER_OBJECT_ID	(StigmaCount		 , 93 )
		REGISTER_OBJECT_ID	(Stone				 , 94 )
		REGISTER_OBJECT_ID	(Stop				 , 95 )
		REGISTER_OBJECT_ID	(SwordExplode		 , 96 )
		REGISTER_OBJECT_ID	(Temptation			 , 97 )
		REGISTER_OBJECT_ID	(Thunder			 , 98 )
		REGISTER_OBJECT_ID	(UltimateBackground	 , 99 )
		REGISTER_OBJECT_ID	(UltimateFog		 , 100)
		REGISTER_OBJECT_ID	(UltimateObject		 , 101)
		REGISTER_OBJECT_ID	(UltimateShuriken	 , 102)
		REGISTER_OBJECT_ID	(Undead				 , 103)
		REGISTER_OBJECT_ID	(UpStat				 , 104)
		REGISTER_OBJECT_ID	(Variation			 , 105)
		REGISTER_OBJECT_ID	(Whiggin			 , 106)
		REGISTER_OBJECT_ID	(White				 , 107)
		REGISTER_OBJECT_ID	(Wind				 , 108)



	}
}

