// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Equip.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Equip_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Equip_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Equip_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Equip_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Equip_2eproto;
namespace Protocol {
class C_EQUIP;
struct C_EQUIPDefaultTypeInternal;
extern C_EQUIPDefaultTypeInternal _C_EQUIP_default_instance_;
class S_EQUIP;
struct S_EQUIPDefaultTypeInternal;
extern S_EQUIPDefaultTypeInternal _S_EQUIP_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_EQUIP* Arena::CreateMaybeMessage<::Protocol::C_EQUIP>(Arena*);
template<> ::Protocol::S_EQUIP* Arena::CreateMaybeMessage<::Protocol::S_EQUIP>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_EQUIP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_EQUIP) */ {
 public:
  inline C_EQUIP() : C_EQUIP(nullptr) {}
  ~C_EQUIP() override;
  explicit constexpr C_EQUIP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_EQUIP(const C_EQUIP& from);
  C_EQUIP(C_EQUIP&& from) noexcept
    : C_EQUIP() {
    *this = ::std::move(from);
  }

  inline C_EQUIP& operator=(const C_EQUIP& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_EQUIP& operator=(C_EQUIP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_EQUIP& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_EQUIP* internal_default_instance() {
    return reinterpret_cast<const C_EQUIP*>(
               &_C_EQUIP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_EQUIP& a, C_EQUIP& b) {
    a.Swap(&b);
  }
  inline void Swap(C_EQUIP* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_EQUIP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_EQUIP* New() const final {
    return new C_EQUIP();
  }

  C_EQUIP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_EQUIP>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_EQUIP& from);
  void MergeFrom(const C_EQUIP& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_EQUIP* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_EQUIP";
  }
  protected:
  explicit C_EQUIP(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSceneLayerPlayeridEquipidFieldNumber = 1,
    kItemIdFieldNumber = 2,
  };
  // uint32 scene_layer_playerid_equipid = 1;
  void clear_scene_layer_playerid_equipid();
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_layer_playerid_equipid() const;
  void set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_scene_layer_playerid_equipid() const;
  void _internal_set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 item_id = 2;
  void clear_item_id();
  ::PROTOBUF_NAMESPACE_ID::int32 item_id() const;
  void set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_item_id() const;
  void _internal_set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_EQUIP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_layer_playerid_equipid_;
  ::PROTOBUF_NAMESPACE_ID::int32 item_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Equip_2eproto;
};
// -------------------------------------------------------------------

class S_EQUIP final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_EQUIP) */ {
 public:
  inline S_EQUIP() : S_EQUIP(nullptr) {}
  ~S_EQUIP() override;
  explicit constexpr S_EQUIP(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_EQUIP(const S_EQUIP& from);
  S_EQUIP(S_EQUIP&& from) noexcept
    : S_EQUIP() {
    *this = ::std::move(from);
  }

  inline S_EQUIP& operator=(const S_EQUIP& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_EQUIP& operator=(S_EQUIP&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_EQUIP& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_EQUIP* internal_default_instance() {
    return reinterpret_cast<const S_EQUIP*>(
               &_S_EQUIP_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_EQUIP& a, S_EQUIP& b) {
    a.Swap(&b);
  }
  inline void Swap(S_EQUIP* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_EQUIP* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_EQUIP* New() const final {
    return new S_EQUIP();
  }

  S_EQUIP* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_EQUIP>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_EQUIP& from);
  void MergeFrom(const S_EQUIP& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_EQUIP* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_EQUIP";
  }
  protected:
  explicit S_EQUIP(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSceneLayerPlayeridEquipidFieldNumber = 1,
    kItemIdFieldNumber = 2,
  };
  // uint32 scene_layer_playerid_equipid = 1;
  void clear_scene_layer_playerid_equipid();
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_layer_playerid_equipid() const;
  void set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_scene_layer_playerid_equipid() const;
  void _internal_set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 item_id = 2;
  void clear_item_id();
  ::PROTOBUF_NAMESPACE_ID::int32 item_id() const;
  void set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_item_id() const;
  void _internal_set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_EQUIP)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_layer_playerid_equipid_;
  ::PROTOBUF_NAMESPACE_ID::int32 item_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Equip_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_EQUIP

// uint32 scene_layer_playerid_equipid = 1;
inline void C_EQUIP::clear_scene_layer_playerid_equipid() {
  scene_layer_playerid_equipid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_EQUIP::_internal_scene_layer_playerid_equipid() const {
  return scene_layer_playerid_equipid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_EQUIP::scene_layer_playerid_equipid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_EQUIP.scene_layer_playerid_equipid)
  return _internal_scene_layer_playerid_equipid();
}
inline void C_EQUIP::_internal_set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  scene_layer_playerid_equipid_ = value;
}
inline void C_EQUIP::set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_scene_layer_playerid_equipid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_EQUIP.scene_layer_playerid_equipid)
}

// int32 item_id = 2;
inline void C_EQUIP::clear_item_id() {
  item_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_EQUIP::_internal_item_id() const {
  return item_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 C_EQUIP::item_id() const {
  // @@protoc_insertion_point(field_get:Protocol.C_EQUIP.item_id)
  return _internal_item_id();
}
inline void C_EQUIP::_internal_set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  item_id_ = value;
}
inline void C_EQUIP::set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:Protocol.C_EQUIP.item_id)
}

// -------------------------------------------------------------------

// S_EQUIP

// uint32 scene_layer_playerid_equipid = 1;
inline void S_EQUIP::clear_scene_layer_playerid_equipid() {
  scene_layer_playerid_equipid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_EQUIP::_internal_scene_layer_playerid_equipid() const {
  return scene_layer_playerid_equipid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_EQUIP::scene_layer_playerid_equipid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EQUIP.scene_layer_playerid_equipid)
  return _internal_scene_layer_playerid_equipid();
}
inline void S_EQUIP::_internal_set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  scene_layer_playerid_equipid_ = value;
}
inline void S_EQUIP::set_scene_layer_playerid_equipid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_scene_layer_playerid_equipid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EQUIP.scene_layer_playerid_equipid)
}

// int32 item_id = 2;
inline void S_EQUIP::clear_item_id() {
  item_id_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 S_EQUIP::_internal_item_id() const {
  return item_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 S_EQUIP::item_id() const {
  // @@protoc_insertion_point(field_get:Protocol.S_EQUIP.item_id)
  return _internal_item_id();
}
inline void S_EQUIP::_internal_set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  item_id_ = value;
}
inline void S_EQUIP::set_item_id(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_item_id(value);
  // @@protoc_insertion_point(field_set:Protocol.S_EQUIP.item_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Equip_2eproto
