// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Equip.proto

#include "Equip.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace Protocol {
constexpr C_EQUIP::C_EQUIP(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : item_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , scene_layer_playerid_(0u)
  , equip_type_(0u){}
struct C_EQUIPDefaultTypeInternal {
  constexpr C_EQUIPDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~C_EQUIPDefaultTypeInternal() {}
  union {
    C_EQUIP _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT C_EQUIPDefaultTypeInternal _C_EQUIP_default_instance_;
constexpr S_EQUIP::S_EQUIP(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : item_name_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , scene_layer_playerid_(0u)
  , equip_type_(0u){}
struct S_EQUIPDefaultTypeInternal {
  constexpr S_EQUIPDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~S_EQUIPDefaultTypeInternal() {}
  union {
    S_EQUIP _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT S_EQUIPDefaultTypeInternal _S_EQUIP_default_instance_;
}  // namespace Protocol
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_Equip_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_Equip_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_Equip_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_Equip_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_EQUIP, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Protocol::C_EQUIP, scene_layer_playerid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C_EQUIP, item_name_),
  PROTOBUF_FIELD_OFFSET(::Protocol::C_EQUIP, equip_type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_EQUIP, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::Protocol::S_EQUIP, scene_layer_playerid_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S_EQUIP, item_name_),
  PROTOBUF_FIELD_OFFSET(::Protocol::S_EQUIP, equip_type_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::Protocol::C_EQUIP)},
  { 8, -1, sizeof(::Protocol::S_EQUIP)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_C_EQUIP_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::Protocol::_S_EQUIP_default_instance_),
};

const char descriptor_table_protodef_Equip_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\013Equip.proto\022\010Protocol\"N\n\007C_EQUIP\022\034\n\024sc"
  "ene_layer_playerid\030\001 \001(\r\022\021\n\titem_name\030\002 "
  "\001(\t\022\022\n\nequip_type\030\003 \001(\r\"N\n\007S_EQUIP\022\034\n\024sc"
  "ene_layer_playerid\030\001 \001(\r\022\021\n\titem_name\030\002 "
  "\001(\t\022\022\n\nequip_type\030\003 \001(\rb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_Equip_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Equip_2eproto = {
  false, false, 191, descriptor_table_protodef_Equip_2eproto, "Equip.proto", 
  &descriptor_table_Equip_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_Equip_2eproto::offsets,
  file_level_metadata_Equip_2eproto, file_level_enum_descriptors_Equip_2eproto, file_level_service_descriptors_Equip_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable* descriptor_table_Equip_2eproto_getter() {
  return &descriptor_table_Equip_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_Equip_2eproto(&descriptor_table_Equip_2eproto);
namespace Protocol {

// ===================================================================

class C_EQUIP::_Internal {
 public:
};

C_EQUIP::C_EQUIP(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.C_EQUIP)
}
C_EQUIP::C_EQUIP(const C_EQUIP& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  item_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_item_name().empty()) {
    item_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_item_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&scene_layer_playerid_, &from.scene_layer_playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&equip_type_) -
    reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
  // @@protoc_insertion_point(copy_constructor:Protocol.C_EQUIP)
}

void C_EQUIP::SharedCtor() {
item_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&scene_layer_playerid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&equip_type_) -
    reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
}

C_EQUIP::~C_EQUIP() {
  // @@protoc_insertion_point(destructor:Protocol.C_EQUIP)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void C_EQUIP::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  item_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void C_EQUIP::ArenaDtor(void* object) {
  C_EQUIP* _this = reinterpret_cast< C_EQUIP* >(object);
  (void)_this;
}
void C_EQUIP::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void C_EQUIP::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void C_EQUIP::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.C_EQUIP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  item_name_.ClearToEmpty();
  ::memset(&scene_layer_playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&equip_type_) -
      reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* C_EQUIP::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 scene_layer_playerid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          scene_layer_playerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string item_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_item_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Protocol.C_EQUIP.item_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 equip_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          equip_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* C_EQUIP::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.C_EQUIP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 scene_layer_playerid = 1;
  if (this->scene_layer_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_scene_layer_playerid(), target);
  }

  // string item_name = 2;
  if (!this->item_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_item_name().data(), static_cast<int>(this->_internal_item_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.C_EQUIP.item_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_item_name(), target);
  }

  // uint32 equip_type = 3;
  if (this->equip_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_equip_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.C_EQUIP)
  return target;
}

size_t C_EQUIP::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.C_EQUIP)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string item_name = 2;
  if (!this->item_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_item_name());
  }

  // uint32 scene_layer_playerid = 1;
  if (this->scene_layer_playerid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_scene_layer_playerid());
  }

  // uint32 equip_type = 3;
  if (this->equip_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_equip_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void C_EQUIP::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.C_EQUIP)
  GOOGLE_DCHECK_NE(&from, this);
  const C_EQUIP* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<C_EQUIP>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.C_EQUIP)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.C_EQUIP)
    MergeFrom(*source);
  }
}

void C_EQUIP::MergeFrom(const C_EQUIP& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.C_EQUIP)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.item_name().empty()) {
    _internal_set_item_name(from._internal_item_name());
  }
  if (from.scene_layer_playerid() != 0) {
    _internal_set_scene_layer_playerid(from._internal_scene_layer_playerid());
  }
  if (from.equip_type() != 0) {
    _internal_set_equip_type(from._internal_equip_type());
  }
}

void C_EQUIP::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.C_EQUIP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void C_EQUIP::CopyFrom(const C_EQUIP& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.C_EQUIP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool C_EQUIP::IsInitialized() const {
  return true;
}

void C_EQUIP::InternalSwap(C_EQUIP* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &item_name_, GetArenaForAllocation(),
      &other->item_name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(C_EQUIP, equip_type_)
      + sizeof(C_EQUIP::equip_type_)
      - PROTOBUF_FIELD_OFFSET(C_EQUIP, scene_layer_playerid_)>(
          reinterpret_cast<char*>(&scene_layer_playerid_),
          reinterpret_cast<char*>(&other->scene_layer_playerid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata C_EQUIP::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Equip_2eproto_getter, &descriptor_table_Equip_2eproto_once,
      file_level_metadata_Equip_2eproto[0]);
}

// ===================================================================

class S_EQUIP::_Internal {
 public:
};

S_EQUIP::S_EQUIP(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:Protocol.S_EQUIP)
}
S_EQUIP::S_EQUIP(const S_EQUIP& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  item_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_item_name().empty()) {
    item_name_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_item_name(), 
      GetArenaForAllocation());
  }
  ::memcpy(&scene_layer_playerid_, &from.scene_layer_playerid_,
    static_cast<size_t>(reinterpret_cast<char*>(&equip_type_) -
    reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
  // @@protoc_insertion_point(copy_constructor:Protocol.S_EQUIP)
}

void S_EQUIP::SharedCtor() {
item_name_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&scene_layer_playerid_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&equip_type_) -
    reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
}

S_EQUIP::~S_EQUIP() {
  // @@protoc_insertion_point(destructor:Protocol.S_EQUIP)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void S_EQUIP::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  item_name_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void S_EQUIP::ArenaDtor(void* object) {
  S_EQUIP* _this = reinterpret_cast< S_EQUIP* >(object);
  (void)_this;
}
void S_EQUIP::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void S_EQUIP::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void S_EQUIP::Clear() {
// @@protoc_insertion_point(message_clear_start:Protocol.S_EQUIP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  item_name_.ClearToEmpty();
  ::memset(&scene_layer_playerid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&equip_type_) -
      reinterpret_cast<char*>(&scene_layer_playerid_)) + sizeof(equip_type_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* S_EQUIP::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 scene_layer_playerid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          scene_layer_playerid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string item_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_item_name();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "Protocol.S_EQUIP.item_name"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint32 equip_type = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          equip_type_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag == 0) || ((tag & 7) == 4)) {
          CHK_(ptr);
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* S_EQUIP::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:Protocol.S_EQUIP)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 scene_layer_playerid = 1;
  if (this->scene_layer_playerid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_scene_layer_playerid(), target);
  }

  // string item_name = 2;
  if (!this->item_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_item_name().data(), static_cast<int>(this->_internal_item_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "Protocol.S_EQUIP.item_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_item_name(), target);
  }

  // uint32 equip_type = 3;
  if (this->equip_type() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(3, this->_internal_equip_type(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:Protocol.S_EQUIP)
  return target;
}

size_t S_EQUIP::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:Protocol.S_EQUIP)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string item_name = 2;
  if (!this->item_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_item_name());
  }

  // uint32 scene_layer_playerid = 1;
  if (this->scene_layer_playerid() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_scene_layer_playerid());
  }

  // uint32 equip_type = 3;
  if (this->equip_type() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_equip_type());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void S_EQUIP::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Protocol.S_EQUIP)
  GOOGLE_DCHECK_NE(&from, this);
  const S_EQUIP* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<S_EQUIP>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Protocol.S_EQUIP)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Protocol.S_EQUIP)
    MergeFrom(*source);
  }
}

void S_EQUIP::MergeFrom(const S_EQUIP& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Protocol.S_EQUIP)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from.item_name().empty()) {
    _internal_set_item_name(from._internal_item_name());
  }
  if (from.scene_layer_playerid() != 0) {
    _internal_set_scene_layer_playerid(from._internal_scene_layer_playerid());
  }
  if (from.equip_type() != 0) {
    _internal_set_equip_type(from._internal_equip_type());
  }
}

void S_EQUIP::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Protocol.S_EQUIP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void S_EQUIP::CopyFrom(const S_EQUIP& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Protocol.S_EQUIP)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool S_EQUIP::IsInitialized() const {
  return true;
}

void S_EQUIP::InternalSwap(S_EQUIP* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      &item_name_, GetArenaForAllocation(),
      &other->item_name_, other->GetArenaForAllocation()
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(S_EQUIP, equip_type_)
      + sizeof(S_EQUIP::equip_type_)
      - PROTOBUF_FIELD_OFFSET(S_EQUIP, scene_layer_playerid_)>(
          reinterpret_cast<char*>(&scene_layer_playerid_),
          reinterpret_cast<char*>(&other->scene_layer_playerid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata S_EQUIP::GetMetadata() const {
  return ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(
      &descriptor_table_Equip_2eproto_getter, &descriptor_table_Equip_2eproto_once,
      file_level_metadata_Equip_2eproto[1]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::Protocol::C_EQUIP* Arena::CreateMaybeMessage< ::Protocol::C_EQUIP >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::C_EQUIP >(arena);
}
template<> PROTOBUF_NOINLINE ::Protocol::S_EQUIP* Arena::CreateMaybeMessage< ::Protocol::S_EQUIP >(Arena* arena) {
  return Arena::CreateMessageInternal< ::Protocol::S_EQUIP >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
