// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Item.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Item_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Item_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3017000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3017001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Item_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Item_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Item_2eproto;
namespace Protocol {
class C_ITEM;
struct C_ITEMDefaultTypeInternal;
extern C_ITEMDefaultTypeInternal _C_ITEM_default_instance_;
class S_ITEM;
struct S_ITEMDefaultTypeInternal;
extern S_ITEMDefaultTypeInternal _S_ITEM_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::C_ITEM* Arena::CreateMaybeMessage<::Protocol::C_ITEM>(Arena*);
template<> ::Protocol::S_ITEM* Arena::CreateMaybeMessage<::Protocol::S_ITEM>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class C_ITEM final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.C_ITEM) */ {
 public:
  inline C_ITEM() : C_ITEM(nullptr) {}
  ~C_ITEM() override;
  explicit constexpr C_ITEM(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  C_ITEM(const C_ITEM& from);
  C_ITEM(C_ITEM&& from) noexcept
    : C_ITEM() {
    *this = ::std::move(from);
  }

  inline C_ITEM& operator=(const C_ITEM& from) {
    CopyFrom(from);
    return *this;
  }
  inline C_ITEM& operator=(C_ITEM&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const C_ITEM& default_instance() {
    return *internal_default_instance();
  }
  static inline const C_ITEM* internal_default_instance() {
    return reinterpret_cast<const C_ITEM*>(
               &_C_ITEM_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(C_ITEM& a, C_ITEM& b) {
    a.Swap(&b);
  }
  inline void Swap(C_ITEM* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(C_ITEM* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline C_ITEM* New() const final {
    return new C_ITEM();
  }

  C_ITEM* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<C_ITEM>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const C_ITEM& from);
  void MergeFrom(const C_ITEM& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(C_ITEM* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.C_ITEM";
  }
  protected:
  explicit C_ITEM(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScenePlayeridItemidFieldNumber = 1,
  };
  // uint32 scene_playerid_itemid = 1;
  void clear_scene_playerid_itemid();
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_playerid_itemid() const;
  void set_scene_playerid_itemid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_scene_playerid_itemid() const;
  void _internal_set_scene_playerid_itemid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.C_ITEM)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_playerid_itemid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Item_2eproto;
};
// -------------------------------------------------------------------

class S_ITEM final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.S_ITEM) */ {
 public:
  inline S_ITEM() : S_ITEM(nullptr) {}
  ~S_ITEM() override;
  explicit constexpr S_ITEM(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  S_ITEM(const S_ITEM& from);
  S_ITEM(S_ITEM&& from) noexcept
    : S_ITEM() {
    *this = ::std::move(from);
  }

  inline S_ITEM& operator=(const S_ITEM& from) {
    CopyFrom(from);
    return *this;
  }
  inline S_ITEM& operator=(S_ITEM&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const S_ITEM& default_instance() {
    return *internal_default_instance();
  }
  static inline const S_ITEM* internal_default_instance() {
    return reinterpret_cast<const S_ITEM*>(
               &_S_ITEM_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(S_ITEM& a, S_ITEM& b) {
    a.Swap(&b);
  }
  inline void Swap(S_ITEM* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(S_ITEM* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline S_ITEM* New() const final {
    return new S_ITEM();
  }

  S_ITEM* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<S_ITEM>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const S_ITEM& from);
  void MergeFrom(const S_ITEM& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(S_ITEM* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.S_ITEM";
  }
  protected:
  explicit S_ITEM(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kScenePlayeridFuncidFieldNumber = 1,
    kItemValueFieldNumber = 2,
  };
  // uint32 scene_playerid_funcid = 1;
  void clear_scene_playerid_funcid();
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_playerid_funcid() const;
  void set_scene_playerid_funcid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_scene_playerid_funcid() const;
  void _internal_set_scene_playerid_funcid(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 item_value = 2;
  void clear_item_value();
  ::PROTOBUF_NAMESPACE_ID::uint32 item_value() const;
  void set_item_value(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_item_value() const;
  void _internal_set_item_value(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.S_ITEM)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 scene_playerid_funcid_;
  ::PROTOBUF_NAMESPACE_ID::uint32 item_value_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_Item_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// C_ITEM

// uint32 scene_playerid_itemid = 1;
inline void C_ITEM::clear_scene_playerid_itemid() {
  scene_playerid_itemid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_ITEM::_internal_scene_playerid_itemid() const {
  return scene_playerid_itemid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 C_ITEM::scene_playerid_itemid() const {
  // @@protoc_insertion_point(field_get:Protocol.C_ITEM.scene_playerid_itemid)
  return _internal_scene_playerid_itemid();
}
inline void C_ITEM::_internal_set_scene_playerid_itemid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  scene_playerid_itemid_ = value;
}
inline void C_ITEM::set_scene_playerid_itemid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_scene_playerid_itemid(value);
  // @@protoc_insertion_point(field_set:Protocol.C_ITEM.scene_playerid_itemid)
}

// -------------------------------------------------------------------

// S_ITEM

// uint32 scene_playerid_funcid = 1;
inline void S_ITEM::clear_scene_playerid_funcid() {
  scene_playerid_funcid_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_ITEM::_internal_scene_playerid_funcid() const {
  return scene_playerid_funcid_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_ITEM::scene_playerid_funcid() const {
  // @@protoc_insertion_point(field_get:Protocol.S_ITEM.scene_playerid_funcid)
  return _internal_scene_playerid_funcid();
}
inline void S_ITEM::_internal_set_scene_playerid_funcid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  scene_playerid_funcid_ = value;
}
inline void S_ITEM::set_scene_playerid_funcid(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_scene_playerid_funcid(value);
  // @@protoc_insertion_point(field_set:Protocol.S_ITEM.scene_playerid_funcid)
}

// uint32 item_value = 2;
inline void S_ITEM::clear_item_value() {
  item_value_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_ITEM::_internal_item_value() const {
  return item_value_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 S_ITEM::item_value() const {
  // @@protoc_insertion_point(field_get:Protocol.S_ITEM.item_value)
  return _internal_item_value();
}
inline void S_ITEM::_internal_set_item_value(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  item_value_ = value;
}
inline void S_ITEM::set_item_value(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_item_value(value);
  // @@protoc_insertion_point(field_set:Protocol.S_ITEM.item_value)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Item_2eproto
